name: threshold
threshold: ${graph.sparsifier.threshold}
binary: ${graph.sparsifier.binary, false}
keep_self_loop: ${graph.sparsifier.keep_self_loop, false}
make_symmetric: ${graph.sparsifier.make_symmetric. true}
