scaled_target: true
max_epochs: 200
batch_size: 32
shuffle_batch: true
samples_per_epoch: 5120

early_stopping:
  monitor: val_mae
  patience: 10
  mode: "min"

logging:
  log_every_n_steps: 16

optim:
  learning_rate: 1e-3
  gradient_clip_algorithm: "norm"
  gradient_clip_val: 0.5

scheduler:
  eta_min: 1e-4
  T_max: ${training.max_epochs}
