defaults:
  - /graph/distance: masked_euclidean
  - /graph/affinity: gaussian_kernel
  - /graph/sparsifier: topk
  - _self_

name: ed_rbf_topk

# Affinity function config
affinity:
  gamma: 0.1

# Sparsifier setting
sparsifier:
  param:
    mode: fraction
    value: ???

label:
