defaults:
  - distance: identity
  - affinity: gaussian_kernel
  - sparsifier: threshold
  - _self_

name: geo_rbf_thresh

distance:
  input: "coordinates"

sparsifier:
  param:
    mode: "absolute"
    value: ???

label:
