defaults:
  - /distance: identity
  - /affinity: gaussian_kernel
  - /sparsifier: threshold
  - _self_

name: geo+gaussian+topk

distance:
  input: "coordinates"

sparsifier:
  param:
    mode: "absolute"
    value: ???

label:
